# Generated by Django 5.0.2 on 2024-02-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_land_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.land')),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='land_images', to='estate.landimage'),
        ),
    ]
