# Generated by Django 5.0.2 on 2024-02-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_remove_land_image_landimage_land_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='images',
        ),
        migrations.AlterField(
            model_name='landimage',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_image', to='estate.land'),
        ),
    ]
