# Generated by Django 5.0.2 on 2024-02-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
    ]
