# Generated by Django 5.0.2 on 2024-02-27 13:07

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_remove_country_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
