# Generated by Django 5.0.2 on 2024-02-27 18:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_countrieslist_alter_building_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
