# Generated by Django 5.0.2 on 2024-02-29 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0024_building_description_land_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='property_id',
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.building'),
            preserve_default=False,
        ),
    ]
