# Generated by Django 5.0.2 on 2024-02-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0025_remove_savedproperty_property_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='property_type',
        ),
    ]
