# Generated by Django 5.0.2 on 2024-02-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0028_alter_savedproperty_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='property',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
