# Generated by Django 5.0.2 on 2024-03-01 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0032_savedproperty_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='price',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='user_id',
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='property_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='estate.building'),
        ),
    ]
