# Generated by Django 5.0.2 on 2024-03-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0033_remove_savedproperty_image_remove_savedproperty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='property_owner',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='user',
        ),
        migrations.AddField(
            model_name='building',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
