# Generated by Django 5.0.2 on 2024-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0034_remove_savedproperty_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.CharField(choices=[('Land', 'land')], default='land', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='category',
            field=models.CharField(choices=[('land', 'Land')], default='land', max_length=20),
        ),
    ]
