# Generated by Django 5.0.2 on 2024-03-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0035_building_category_land_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.CharField(choices=[('building', 'Building')], default='land', max_length=20),
        ),
    ]
