# Generated by Django 5.0.2 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0036_alter_building_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.CharField(choices=[('building', 'Building')], default='building', max_length=20),
        ),
    ]
