# Generated by Django 5.0.2 on 2024-03-05 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0038_testnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNew',
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estate.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('user', 'building')},
        ),
    ]
