# Generated by Django 5.0.2 on 2024-03-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0039_delete_testnew_savedproperty_building_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SavedLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
