# Generated by Django 5.0.2 on 2024-03-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0042_remove_savedproperty_is_saved_building_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_saved',
        ),
    ]
