# Generated by Django 5.0.2 on 2024-03-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0043_remove_building_is_saved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('user', 'building')},
        ),
    ]
