# Generated by Django 5.0.2 on 2024-03-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0044_alter_savedproperty_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedland',
            unique_together={('user', 'land')},
        ),
    ]
