# Generated by Django 5.0.2 on 2024-03-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0045_alter_savedland_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='cart',
        ),
    ]
