# Generated by Django 5.0.2 on 2024-03-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0048_rename_images_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landimage',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.land'),
        ),
    ]
