# Generated by Django 5.0.2 on 2024-03-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0049_alter_landimage_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
    ]
